# Generated by Django 5.2 on 2025-05-05 22:40

import EthicalpulsApp.validators
import django.db.models.deletion
import django.utils.timezone
import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('project_type', models.CharField(choices=[('web', 'Application Web'), ('api', 'API'), ('mobile', 'Application Mobile'), ('infra', 'Infrastructure Réseau'), ('desktop', 'Application Desktop'), ('autre', 'Autre')], max_length=20, verbose_name='Type de projet')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de domaine')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, validators=[EthicalpulsApp.validators.validate_ip], verbose_name='Adresse IP')),
                ('url', models.URLField(blank=True, null=True, validators=[EthicalpulsApp.validators.validate_url], verbose_name='URL')),
                ('scope', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, validators=[EthicalpulsApp.validators.validate_mac], verbose_name='Adresse MAC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scan_type', models.CharField(choices=[('FULL', 'Scan complet'), ('TARGETED', 'Scan ciblé'), ('API', 'Scan API'), ('INFRA', "Scan d'infrastructure")], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('scheduled', 'Planifié'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='scheduled', max_length=20)),
                ('target_url', models.URLField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_scan', models.DateTimeField(blank=True, null=True)),
                ('findings_summary', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='EthicalpulsApp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('PROJECT_MANAGER', 'Chef de projet'), ('DEVELOPER', 'Développeur'), ('SECURITY_ANALYST', 'Analyste sécurité')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_secret', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
