# Generated by Django 5.2 on 2025-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicalpulsApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('analyst', 'Analyste'), ('tester', 'Testeur'), ('viewer', 'Observateur')], default='viewer', max_length=20),
        ),
    ]
